---
name: Docker Build Action
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GOLANG_VERSION: 1.21

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest

    steps:
    - name: Log in to the container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GOLANG_VERSION }}

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        args: --build-tags integration -p bugs -p unused --timeout=3m

    - name: Make tag
      run: |
        echo "tag=latest" >> $GITHUB_ENV

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: .
        build-args: |
          GOLANG_VERSION=${{ env.GOLANG_VERSION }}
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.tag }}
